/**
 * Dayflow HRMS - Master Mock Dataset
 * Contains realistic enterprise workforce records, attendance logs, leave requests, and salary structures.
 */

export const INITIAL_SALARY_COMPONENTS = [
  {
    id: 'COMP-01',
    name: 'Basic Salary',
    type: 'Percentage',
    value: 50,
    basedOn: 'Monthly Wage',
    enabled: true,
    category: 'Earning'
  },
  {
    id: 'COMP-02',
    name: 'House Rent Allowance (HRA)',
    type: 'Percentage',
    value: 50,
    basedOn: 'Basic Salary',
    enabled: true,
    category: 'Earning'
  },
  {
    id: 'COMP-03',
    name: 'Standard Allowance',
    type: 'Fixed',
    value: 4167,
    basedOn: 'Monthly Wage',
    enabled: true,
    category: 'Earning'
  },
  {
    id: 'COMP-04',
    name: 'Performance Bonus',
    type: 'Percentage',
    value: 8.33,
    basedOn: 'Basic Salary',
    enabled: true,
    category: 'Earning'
  },
  {
    id: 'COMP-05',
    name: 'Leave Travel Allowance (LTA)',
    type: 'Fixed',
    value: 3000,
    basedOn: 'Monthly Wage',
    enabled: true,
    category: 'Earning'
  },
  {
    id: 'COMP-06',
    name: 'Special / Fixed Allowance',
    type: 'Fixed',
    value: 5000,
    basedOn: 'Monthly Wage',
    enabled: false,
    category: 'Earning'
  }
];

export const INITIAL_EMPLOYEES = [
  {
    id: 'EMP-1001',
    name: 'Aarav Sharma',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Senior Full Stack Engineer',
    department: 'Engineering',
    manager: 'Vikram Malhotra',
    employmentType: 'Full-time',
    attendanceStatus: 'Present',
    workEmail: 'aarav.sharma@dayflow.io',
    personalEmail: 'aarav.sharma.dev@gmail.com',
    phone: '+91 98765 43210',
    emergencyContact: '+91 98765 43211 (Spouse)',
    dob: '1992-05-14',
    gender: 'Male',
    nationality: 'Indian',
    maritalStatus: 'Married',
    joiningDate: '2021-03-15',
    officeLocation: 'Bangalore HQ (Tower 4)',
    team: 'Core Platform Team',
    workSchedule: 'General Shift (09:00 AM - 06:00 PM)',
    address: 'Flat 402, Green Glen Layout, Bellandur',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    // Sensitive / Private HR Info
    pan: 'ABCDE1234F',
    uan: '100987654321',
    bankAccount: '918273645012',
    bankName: 'HDFC Bank Ltd',
    ifsc: 'HDFC0001234',
    dependents: '2 (Spouse, Child)',
    benefits: 'Comprehensive Health Insurance (₹5L), Wellness Reimbursement',
    // Salary configuration
    monthlyWage: 120000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1002',
    name: 'Priya Patel',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'HR Operations Specialist',
    department: 'Human Resources',
    manager: 'Ananya Deshmukh',
    employmentType: 'Full-time',
    attendanceStatus: 'Present',
    workEmail: 'priya.patel@dayflow.io',
    personalEmail: 'priya.patel.hr@gmail.com',
    phone: '+91 98112 23344',
    emergencyContact: '+91 98112 23345 (Father)',
    dob: '1995-11-20',
    gender: 'Female',
    nationality: 'Indian',
    maritalStatus: 'Single',
    joiningDate: '2022-07-01',
    officeLocation: 'Mumbai Hub',
    team: 'People & Culture',
    workSchedule: 'General Shift (09:30 AM - 06:30 PM)',
    address: 'B-12, Palm Beach Residency, Vashi',
    city: 'Navi Mumbai',
    state: 'Maharashtra',
    country: 'India',
    pan: 'BKMPP5678K',
    uan: '101234567890',
    bankAccount: '50100234567891',
    bankName: 'ICICI Bank',
    ifsc: 'ICIC0000021',
    dependents: 'None',
    benefits: 'Medical Floater, Parental Support',
    monthlyWage: 65000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1003',
    name: 'Rohan Mehta',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Lead Financial Analyst',
    department: 'Finance',
    manager: 'Siddharth Sen',
    employmentType: 'Full-time',
    attendanceStatus: 'Present',
    workEmail: 'rohan.mehta@dayflow.io',
    personalEmail: 'rohan.mehta.fin@gmail.com',
    phone: '+91 97234 56789',
    emergencyContact: '+91 97234 56790 (Brother)',
    dob: '1990-08-12',
    gender: 'Male',
    nationality: 'Indian',
    maritalStatus: 'Married',
    joiningDate: '2020-01-10',
    officeLocation: 'Mumbai Hub',
    team: 'Treasury & Audit',
    workSchedule: 'General Shift (09:00 AM - 06:00 PM)',
    address: '703, Symphony Heights, Andheri West',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    pan: 'CPPRM9876Q',
    uan: '100456789123',
    bankAccount: '001201567890',
    bankName: 'Axis Bank',
    ifsc: 'UTIB0000012',
    dependents: '1 (Spouse)',
    benefits: 'Executive Health Cover, Stock Options',
    monthlyWage: 140000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1004',
    name: 'Neha Verma',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Enterprise Account Executive',
    department: 'Sales',
    manager: 'Rajesh Nair',
    employmentType: 'Full-time',
    attendanceStatus: 'On Approved Leave',
    workEmail: 'neha.verma@dayflow.io',
    personalEmail: 'neha.v.sales@gmail.com',
    phone: '+91 96543 21098',
    emergencyContact: '+91 96543 21099 (Mother)',
    dob: '1994-03-25',
    gender: 'Female',
    nationality: 'Indian',
    maritalStatus: 'Single',
    joiningDate: '2023-02-15',
    officeLocation: 'Delhi NCR Office',
    team: 'North Enterprise Sales',
    workSchedule: 'Flexible Field (09:00 AM - 06:00 PM)',
    address: 'Tower C, DLF Phase 5, CyberCity',
    city: 'Gurugram',
    state: 'Haryana',
    country: 'India',
    pan: 'EPPNV4567M',
    uan: '100789123456',
    bankAccount: '123405009876',
    bankName: 'Kotak Mahindra Bank',
    ifsc: 'KKBK0000180',
    dependents: 'None',
    benefits: 'Sales Travel Allowance, Premium OPD',
    monthlyWage: 95000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1005',
    name: 'Devansh Kulkarni',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'DevOps & Cloud Architect',
    department: 'Engineering',
    manager: 'Vikram Malhotra',
    employmentType: 'Full-time',
    attendanceStatus: 'Present',
    workEmail: 'devansh.k@dayflow.io',
    personalEmail: 'devansh.infra@gmail.com',
    phone: '+91 95432 10987',
    emergencyContact: '+91 95432 10988 (Spouse)',
    dob: '1989-10-05',
    gender: 'Male',
    nationality: 'Indian',
    maritalStatus: 'Married',
    joiningDate: '2019-11-01',
    officeLocation: 'Bangalore HQ (Tower 4)',
    team: 'Infrastructure & SRE',
    workSchedule: 'On-Call Rotation (09:00 AM - 06:00 PM)',
    address: 'Villa 18, Ferns Meadows, Hennur Road',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    pan: 'FPKDK3456Z',
    uan: '100654321789',
    bankAccount: '601982736451',
    bankName: 'State Bank of India',
    ifsc: 'SBIN0008765',
    dependents: '3 (Spouse, 2 Children)',
    benefits: 'Family Floater ₹10L, Home Office Setup',
    monthlyWage: 165000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1006',
    name: 'Sneha Rao',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Brand & Product Marketer',
    department: 'Marketing',
    manager: 'Tanvi Iyer',
    employmentType: 'Full-time',
    attendanceStatus: 'On Break',
    workEmail: 'sneha.rao@dayflow.io',
    personalEmail: 'sneha.rao.mkt@gmail.com',
    phone: '+91 94321 09876',
    emergencyContact: '+91 94321 09877 (Mother)',
    dob: '1996-04-18',
    gender: 'Female',
    nationality: 'Indian',
    maritalStatus: 'Single',
    joiningDate: '2023-05-10',
    officeLocation: 'Bangalore HQ (Tower 4)',
    team: 'Growth Marketing',
    workSchedule: 'General Shift (10:00 AM - 07:00 PM)',
    address: 'Flat 204, Salarpuria Sattva, Indiranagar',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    pan: 'GPSR8765B',
    uan: '101987654322',
    bankAccount: '112233445566',
    bankName: 'HDFC Bank Ltd',
    ifsc: 'HDFC0001234',
    dependents: 'None',
    benefits: 'Learning Stipend, Health Insurance',
    monthlyWage: 70000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1007',
    name: 'Kabir Singhania',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Supply Chain Coordinator',
    department: 'Operations',
    manager: 'Manoj Kumar',
    employmentType: 'Contract',
    attendanceStatus: 'Present',
    workEmail: 'kabir.s@dayflow.io',
    personalEmail: 'kabir.singh.ops@gmail.com',
    phone: '+91 93210 98765',
    emergencyContact: '+91 93210 98766 (Brother)',
    dob: '1993-09-30',
    gender: 'Male',
    nationality: 'Indian',
    maritalStatus: 'Single',
    joiningDate: '2023-08-01',
    officeLocation: 'Pune Logistics Park',
    team: 'Fulfillment & Logistics',
    workSchedule: 'Shift A (08:00 AM - 05:00 PM)',
    address: 'Rowhouse 9, Magarpatta City',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    pan: 'HPKKS2345T',
    uan: '100876543219',
    bankAccount: '998877665544',
    bankName: 'Bank of Baroda',
    ifsc: 'BARB0VIMANP',
    dependents: 'Parents',
    benefits: 'Workplace Safety Cover, Accidental Insurance',
    monthlyWage: 48000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 6,
    breakTime: '45 Mins',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1008',
    name: 'Ananya Deshmukh',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'VP of Human Resources',
    department: 'Human Resources',
    manager: 'Executive Board',
    employmentType: 'Full-time',
    attendanceStatus: 'Present',
    workEmail: 'ananya.d@dayflow.io',
    personalEmail: 'ananya.deshmukh.exec@gmail.com',
    phone: '+91 92109 87654',
    emergencyContact: '+91 92109 87655 (Spouse)',
    dob: '1985-02-14',
    gender: 'Female',
    nationality: 'Indian',
    maritalStatus: 'Married',
    joiningDate: '2018-06-01',
    officeLocation: 'Bangalore HQ (Tower 4)',
    team: 'Executive Leadership',
    workSchedule: 'General Shift (09:00 AM - 06:00 PM)',
    address: 'Penthouse 12, Prestige Golfshire, Nandi Hills Road',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    pan: 'JPKAD1122C',
    uan: '100112233445',
    bankAccount: '445566778899',
    bankName: 'Standard Chartered',
    ifsc: 'SCBL0036001',
    dependents: '2 (Spouse, Child)',
    benefits: 'Executive Healthcare, Stock Options, Annual Executive Checkup',
    monthlyWage: 250000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1009',
    name: 'Tanya Banerjee',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'UI/UX Design Lead',
    department: 'Engineering',
    manager: 'Vikram Malhotra',
    employmentType: 'Full-time',
    attendanceStatus: 'Present',
    workEmail: 'tanya.b@dayflow.io',
    personalEmail: 'tanya.designs@gmail.com',
    phone: '+91 91098 76543',
    emergencyContact: '+91 91098 76544 (Sister)',
    dob: '1993-12-04',
    gender: 'Female',
    nationality: 'Indian',
    maritalStatus: 'Single',
    joiningDate: '2021-09-15',
    officeLocation: 'Bangalore HQ (Tower 4)',
    team: 'Design Systems & UX',
    workSchedule: 'General Shift (09:30 AM - 06:30 PM)',
    address: 'Flat 301, Brigade Millennium, JP Nagar',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    pan: 'KPTTB9988X',
    uan: '100998877665',
    bankAccount: '778899001122',
    bankName: 'HDFC Bank Ltd',
    ifsc: 'HDFC0001234',
    dependents: 'None',
    benefits: 'Wellness Allowance, Device Upgrade Program',
    monthlyWage: 110000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1010',
    name: 'Karthik Raman',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Backend Systems Engineer',
    department: 'Engineering',
    manager: 'Vikram Malhotra',
    employmentType: 'Full-time',
    attendanceStatus: 'Checked Out',
    workEmail: 'karthik.r@dayflow.io',
    personalEmail: 'karthik.raman.code@gmail.com',
    phone: '+91 90987 65432',
    emergencyContact: '+91 90987 65433 (Father)',
    dob: '1995-07-22',
    gender: 'Male',
    nationality: 'Indian',
    maritalStatus: 'Single',
    joiningDate: '2022-04-18',
    officeLocation: 'Chennai Tech Park',
    team: 'Data Engineering',
    workSchedule: 'General Shift (09:00 AM - 06:00 PM)',
    address: 'Plot 45, Velachery Main Road',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    pan: 'LPKKR7766Y',
    uan: '100776655443',
    bankAccount: '334455667788',
    bankName: 'Kotak Mahindra Bank',
    ifsc: 'KKBK0008450',
    dependents: 'Parents',
    benefits: 'Health Insurance, Internet Reimbursement',
    monthlyWage: 85000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1011',
    name: 'Meera Nambiar',
    avatar: 'https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Corporate Legal Counsel',
    department: 'Finance',
    manager: 'Siddharth Sen',
    employmentType: 'Full-time',
    attendanceStatus: 'Present',
    workEmail: 'meera.n@dayflow.io',
    personalEmail: 'meera.nambiar.law@gmail.com',
    phone: '+91 89876 54321',
    emergencyContact: '+91 89876 54322 (Spouse)',
    dob: '1988-06-19',
    gender: 'Female',
    nationality: 'Indian',
    maritalStatus: 'Married',
    joiningDate: '2021-12-01',
    officeLocation: 'Mumbai Hub',
    team: 'Compliance & Governance',
    workSchedule: 'General Shift (09:30 AM - 06:30 PM)',
    address: 'Flat 1102, Rustomjee Seasons, BKC',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    pan: 'MPKMN6655R',
    uan: '100665544332',
    bankAccount: '889900112233',
    bankName: 'HDFC Bank Ltd',
    ifsc: 'HDFC0000456',
    dependents: '1 (Spouse)',
    benefits: 'Legal Research Grants, Comprehensive Health Cover',
    monthlyWage: 135000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1012',
    name: 'Arjun Das',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Digital Marketing Specialist',
    department: 'Marketing',
    manager: 'Tanvi Iyer',
    employmentType: 'Part-time',
    attendanceStatus: 'Not Started / Offline',
    workEmail: 'arjun.das@dayflow.io',
    personalEmail: 'arjun.growth@gmail.com',
    phone: '+91 88765 43210',
    emergencyContact: '+91 88765 43211 (Mother)',
    dob: '1998-01-15',
    gender: 'Male',
    nationality: 'Indian',
    maritalStatus: 'Single',
    joiningDate: '2024-01-10',
    officeLocation: 'Remote',
    team: 'Paid Media & SEO',
    workSchedule: 'Flexible Part-time (20 hrs/week)',
    address: '42, Salt Lake Sector 5',
    city: 'Kolkata',
    state: 'West Bengal',
    country: 'India',
    pan: 'NPKAD5544P',
    uan: '100554433221',
    bankAccount: '223344556677',
    bankName: 'ICICI Bank',
    ifsc: 'ICIC0000104',
    dependents: 'None',
    benefits: 'Co-working Pass, Health Cover',
    monthlyWage: 38000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 4,
    breakTime: '30 Mins',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1013',
    name: 'Ishaan Joshi',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'QA Automation Engineer',
    department: 'Engineering',
    manager: 'Vikram Malhotra',
    employmentType: 'Full-time',
    attendanceStatus: 'Present',
    workEmail: 'ishaan.j@dayflow.io',
    personalEmail: 'ishaan.testing@gmail.com',
    phone: '+91 87654 32109',
    emergencyContact: '+91 87654 32110 (Father)',
    dob: '1996-09-08',
    gender: 'Male',
    nationality: 'Indian',
    maritalStatus: 'Single',
    joiningDate: '2022-10-01',
    officeLocation: 'Bangalore HQ (Tower 4)',
    team: 'Quality Engineering',
    workSchedule: 'General Shift (09:00 AM - 06:00 PM)',
    address: 'Flat 502, Godrej Woodsman Estate, Hebbal',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    pan: 'OPKIJ4433M',
    uan: '100443322110',
    bankAccount: '667788990011',
    bankName: 'State Bank of India',
    ifsc: 'SBIN0001423',
    dependents: 'None',
    benefits: 'Certification Sponsorship, Health Insurance',
    monthlyWage: 75000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1014',
    name: 'Zoya Khan',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'HR Recruitment Specialist',
    department: 'Human Resources',
    manager: 'Ananya Deshmukh',
    employmentType: 'Full-time',
    attendanceStatus: 'Present',
    workEmail: 'zoya.khan@dayflow.io',
    personalEmail: 'zoya.recruits@gmail.com',
    phone: '+91 86543 21098',
    emergencyContact: '+91 86543 21099 (Spouse)',
    dob: '1993-04-12',
    gender: 'Female',
    nationality: 'Indian',
    maritalStatus: 'Married',
    joiningDate: '2022-02-14',
    officeLocation: 'Bangalore HQ (Tower 4)',
    team: 'Talent Acquisition',
    workSchedule: 'General Shift (09:00 AM - 06:00 PM)',
    address: 'Villa 7, Sobha Cinnamon, Harlur Road',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    pan: 'PPKZK3322L',
    uan: '100332211009',
    bankAccount: '556677889900',
    bankName: 'Axis Bank',
    ifsc: 'UTIB0000542',
    dependents: '1 (Spouse)',
    benefits: 'Recruiter Incentives, Full Family Medical Cover',
    monthlyWage: 68000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1015',
    name: 'Aditya Sen',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Solutions Architect',
    department: 'Engineering',
    manager: 'Vikram Malhotra',
    employmentType: 'Full-time',
    attendanceStatus: 'Present',
    workEmail: 'aditya.sen@dayflow.io',
    personalEmail: 'aditya.architect@gmail.com',
    phone: '+91 85432 10987',
    emergencyContact: '+91 85432 10988 (Spouse)',
    dob: '1987-11-28',
    gender: 'Male',
    nationality: 'Indian',
    maritalStatus: 'Married',
    joiningDate: '2020-05-15',
    officeLocation: 'Bangalore HQ (Tower 4)',
    team: 'Architecture Review Board',
    workSchedule: 'General Shift (09:00 AM - 06:00 PM)',
    address: 'B-804, Adarsh Palm Retreat, Outer Ring Road',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    pan: 'QPKAS2211K',
    uan: '100221100998',
    bankAccount: '445566770011',
    bankName: 'HDFC Bank Ltd',
    ifsc: 'HDFC0001234',
    dependents: '3 (Spouse, 2 Children)',
    benefits: 'Executive Health Cover, Conference Sponsorship',
    monthlyWage: 180000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1016',
    name: 'Pooja Hegde',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Facilities & Ops Lead',
    department: 'Operations',
    manager: 'Manoj Kumar',
    employmentType: 'Full-time',
    attendanceStatus: 'On Approved Leave',
    workEmail: 'pooja.h@dayflow.io',
    personalEmail: 'pooja.hegde.ops@gmail.com',
    phone: '+91 84321 09876',
    emergencyContact: '+91 84321 09877 (Father)',
    dob: '1994-08-30',
    gender: 'Female',
    nationality: 'Indian',
    maritalStatus: 'Single',
    joiningDate: '2022-08-15',
    officeLocation: 'Bangalore HQ (Tower 4)',
    team: 'Workplace Operations',
    workSchedule: 'General Shift (08:30 AM - 05:30 PM)',
    address: 'Flat 102, Casa Grand, Whitefield',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    pan: 'RPKPH1100J',
    uan: '100110099887',
    bankAccount: '332211009988',
    bankName: 'Canara Bank',
    ifsc: 'CNRB0002145',
    dependents: 'Parents',
    benefits: 'Commute Allowance, Health Cover',
    monthlyWage: 62000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1017',
    name: 'Siddharth Sen',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Head of Finance',
    department: 'Finance',
    manager: 'Executive Board',
    employmentType: 'Full-time',
    attendanceStatus: 'Present',
    workEmail: 'siddharth.s@dayflow.io',
    personalEmail: 'siddharth.sen.cfo@gmail.com',
    phone: '+91 83210 98765',
    emergencyContact: '+91 83210 98766 (Spouse)',
    dob: '1984-01-20',
    gender: 'Male',
    nationality: 'Indian',
    maritalStatus: 'Married',
    joiningDate: '2019-03-01',
    officeLocation: 'Mumbai Hub',
    team: 'Finance Leadership',
    workSchedule: 'General Shift (09:00 AM - 06:00 PM)',
    address: '15A, Sea Face Towers, Worli',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    pan: 'SPKSS0099H',
    uan: '100009988776',
    bankAccount: '110099887766',
    bankName: 'Citibank N.A.',
    ifsc: 'CITI0000003',
    dependents: '2 (Spouse, Child)',
    benefits: 'Executive Floater ₹15L, ESOPs',
    monthlyWage: 230000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  },
  {
    id: 'EMP-1018',
    name: 'Naveen Choudhury',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    jobTitle: 'Junior Frontend Intern',
    department: 'Engineering',
    manager: 'Aarav Sharma',
    employmentType: 'Intern',
    attendanceStatus: 'Present',
    workEmail: 'naveen.c@dayflow.io',
    personalEmail: 'naveen.intern@gmail.com',
    phone: '+91 82109 87654',
    emergencyContact: '+91 82109 87655 (Father)',
    dob: '2002-06-11',
    gender: 'Male',
    nationality: 'Indian',
    maritalStatus: 'Single',
    joiningDate: '2024-06-01',
    officeLocation: 'Bangalore HQ (Tower 4)',
    team: 'Core Platform Team',
    workSchedule: 'General Shift (09:30 AM - 06:30 PM)',
    address: 'Hostel Block B, IIIT Bangalore, Electronic City',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    pan: 'TPKNC9988G',
    uan: '100998811223',
    bankAccount: '998811223344',
    bankName: 'State Bank of India',
    ifsc: 'SBIN0005123',
    dependents: 'None',
    benefits: 'Internship Stipend, Meal Passes',
    monthlyWage: 30000,
    payFrequency: 'Monthly',
    workingDaysPerWeek: 5,
    breakTime: '1 Hour',
    components: JSON.parse(JSON.stringify(INITIAL_SALARY_COMPONENTS))
  }
];

export const INITIAL_ATTENDANCE_RECORDS = [
  {
    id: 'ATT-101',
    employeeId: 'EMP-1001',
    employeeName: 'Aarav Sharma',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: '09:02 AM',
    checkOut: '06:01 PM',
    totalHours: '8h 59m',
    status: 'Present',
    late: 'No',
    overtime: 'No'
  },
  {
    id: 'ATT-102',
    employeeId: 'EMP-1002',
    employeeName: 'Priya Patel',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    date: '2026-08-22',
    checkIn: '09:34 AM',
    checkOut: '06:15 PM',
    totalHours: '8h 41m',
    status: 'Present',
    late: 'Yes (14m)',
    overtime: 'No'
  },
  {
    id: 'ATT-103',
    employeeId: 'EMP-1003',
    employeeName: 'Rohan Mehta',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Finance',
    date: '2026-08-22',
    checkIn: '08:55 AM',
    checkOut: '06:30 PM',
    totalHours: '9h 35m',
    status: 'Present',
    late: 'No',
    overtime: 'Yes (35m)'
  },
  {
    id: 'ATT-104',
    employeeId: 'EMP-1004',
    employeeName: 'Neha Verma',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    department: 'Sales',
    date: '2026-08-22',
    checkIn: '-',
    checkOut: '-',
    totalHours: '0h 00m',
    status: 'On Approved Leave',
    late: 'No',
    overtime: 'No'
  },
  {
    id: 'ATT-105',
    employeeId: 'EMP-1005',
    employeeName: 'Devansh Kulkarni',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: '09:10 AM',
    checkOut: '07:15 PM',
    totalHours: '10h 05m',
    status: 'Present',
    late: 'No',
    overtime: 'Yes (1h 05m)'
  },
  {
    id: 'ATT-106',
    employeeId: 'EMP-1006',
    employeeName: 'Sneha Rao',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    date: '2026-08-22',
    checkIn: '10:05 AM',
    checkOut: '01:30 PM (Break)',
    totalHours: '3h 25m',
    status: 'On Break',
    late: 'Yes (5m)',
    overtime: 'No'
  },
  {
    id: 'ATT-107',
    employeeId: 'EMP-1007',
    employeeName: 'Kabir Singhania',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    department: 'Operations',
    date: '2026-08-22',
    checkIn: '07:58 AM',
    checkOut: '05:05 PM',
    totalHours: '9h 07m',
    status: 'Present',
    late: 'No',
    overtime: 'No'
  },
  {
    id: 'ATT-108',
    employeeId: 'EMP-1008',
    employeeName: 'Ananya Deshmukh',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    date: '2026-08-22',
    checkIn: '08:50 AM',
    checkOut: '06:10 PM',
    totalHours: '9h 20m',
    status: 'Present',
    late: 'No',
    overtime: 'No'
  },
  {
    id: 'ATT-109',
    employeeId: 'EMP-1009',
    employeeName: 'Tanya Banerjee',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: '09:25 AM',
    checkOut: '06:30 PM',
    totalHours: '9h 05m',
    status: 'Present',
    late: 'No',
    overtime: 'No'
  },
  {
    id: 'ATT-110',
    employeeId: 'EMP-1010',
    employeeName: 'Karthik Raman',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: '09:00 AM',
    checkOut: '05:45 PM',
    totalHours: '8h 45m',
    status: 'Checked Out',
    late: 'No',
    overtime: 'No'
  },
  {
    id: 'ATT-111',
    employeeId: 'EMP-1011',
    employeeName: 'Meera Nambiar',
    avatar: 'https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=150&auto=format&fit=crop&q=80',
    department: 'Finance',
    date: '2026-08-22',
    checkIn: '09:30 AM',
    checkOut: '06:35 PM',
    totalHours: '9h 05m',
    status: 'Present',
    late: 'No',
    overtime: 'No'
  },
  {
    id: 'ATT-112',
    employeeId: 'EMP-1012',
    employeeName: 'Arjun Das',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    date: '2026-08-22',
    checkIn: '-',
    checkOut: '-',
    totalHours: '0h 00m',
    status: 'Not Started / Offline',
    late: 'No',
    overtime: 'No'
  },
  {
    id: 'ATT-113',
    employeeId: 'EMP-1013',
    employeeName: 'Ishaan Joshi',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: '08:58 AM',
    checkOut: '06:05 PM',
    totalHours: '9h 07m',
    status: 'Present',
    late: 'No',
    overtime: 'No'
  },
  {
    id: 'ATT-114',
    employeeId: 'EMP-1014',
    employeeName: 'Zoya Khan',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    date: '2026-08-22',
    checkIn: '09:05 AM',
    checkOut: '06:00 PM',
    totalHours: '8h 55m',
    status: 'Present',
    late: 'Yes (5m)',
    overtime: 'No'
  },
  {
    id: 'ATT-115',
    employeeId: 'EMP-1015',
    employeeName: 'Aditya Sen',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: '09:00 AM',
    checkOut: '06:00 PM',
    totalHours: '9h 00m',
    status: 'Present',
    late: 'No',
    overtime: 'No'
  },
  {
    id: 'ATT-116',
    employeeId: 'EMP-1016',
    employeeName: 'Pooja Hegde',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    department: 'Operations',
    date: '2026-08-22',
    checkIn: '-',
    checkOut: '-',
    totalHours: '0h 00m',
    status: 'On Approved Leave',
    late: 'No',
    overtime: 'No'
  },
  {
    id: 'ATT-117',
    employeeId: 'EMP-1017',
    employeeName: 'Siddharth Sen',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    department: 'Finance',
    date: '2026-08-22',
    checkIn: '08:45 AM',
    checkOut: '06:15 PM',
    totalHours: '9h 30m',
    status: 'Present',
    late: 'No',
    overtime: 'Yes (15m)'
  },
  {
    id: 'ATT-118',
    employeeId: 'EMP-1018',
    employeeName: 'Naveen Choudhury',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: '09:28 AM',
    checkOut: '06:30 PM',
    totalHours: '9h 02m',
    status: 'Present',
    late: 'No',
    overtime: 'No'
  }
];

export const INITIAL_LEAVE_REQUESTS = [
  {
    id: 'LV-501',
    employeeId: 'EMP-1001',
    employeeName: 'Aarav Sharma',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    leaveType: 'Casual Leave',
    startDate: '2026-08-25',
    endDate: '2026-08-26',
    days: 2,
    reason: 'Family wedding function in hometown.',
    status: 'Pending',
    submittedDate: '2026-08-21',
    rejectReason: null
  },
  {
    id: 'LV-502',
    employeeId: 'EMP-1006',
    employeeName: 'Sneha Rao',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    leaveType: 'Sick Leave',
    startDate: '2026-08-24',
    endDate: '2026-08-24',
    days: 1,
    reason: 'Dental checkup and minor procedure scheduled.',
    status: 'Pending',
    submittedDate: '2026-08-22',
    rejectReason: null
  },
  {
    id: 'LV-503',
    employeeId: 'EMP-1007',
    employeeName: 'Kabir Singhania',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    department: 'Operations',
    leaveType: 'Paid Time Off',
    startDate: '2026-08-28',
    endDate: '2026-08-30',
    days: 3,
    reason: 'Personal travel and renewal of residence lease.',
    status: 'Pending',
    submittedDate: '2026-08-20',
    rejectReason: null
  },
  {
    id: 'LV-504',
    employeeId: 'EMP-1004',
    employeeName: 'Neha Verma',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    department: 'Sales',
    leaveType: 'Annual Vacation',
    startDate: '2026-08-20',
    endDate: '2026-08-23',
    days: 4,
    reason: 'Pre-planned family vacation to Himachal.',
    status: 'Approved',
    submittedDate: '2026-08-10',
    approvedBy: 'HR Administrator',
    approvedDate: '2026-08-11',
    rejectReason: null
  },
  {
    id: 'LV-505',
    employeeId: 'EMP-1016',
    employeeName: 'Pooja Hegde',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    department: 'Operations',
    leaveType: 'Sick Leave',
    startDate: '2026-08-22',
    endDate: '2026-08-22',
    days: 1,
    reason: 'Viral fever and doctor consultation.',
    status: 'Approved',
    submittedDate: '2026-08-21',
    approvedBy: 'HR Administrator',
    approvedDate: '2026-08-21',
    rejectReason: null
  },
  {
    id: 'LV-506',
    employeeId: 'EMP-1010',
    employeeName: 'Karthik Raman',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    leaveType: 'Casual Leave',
    startDate: '2026-08-15',
    endDate: '2026-08-16',
    days: 2,
    reason: 'Extended holiday weekend trip.',
    status: 'Rejected',
    submittedDate: '2026-08-12',
    rejectedBy: 'HR Administrator',
    rejectedDate: '2026-08-13',
    rejectReason: 'Critical database migration scheduled on that sprint weekend.'
  }
];

export const INITIAL_ACTIVITY_LOGS = [
  {
    id: 'ACT-1',
    type: 'attendance',
    text: 'Aarav Sharma checked in at 09:02 AM (On Time)',
    time: '2 hours ago',
    icon: 'LogIn',
    color: 'green'
  },
  {
    id: 'ACT-2',
    type: 'leave',
    text: 'Sneha Rao submitted a Sick Leave request for Aug 24',
    time: '3 hours ago',
    icon: 'Calendar',
    color: 'amber'
  },
  {
    id: 'ACT-3',
    type: 'salary',
    text: 'Salary structure updated for Devansh Kulkarni by HR Admin',
    time: '5 hours ago',
    icon: 'CreditCard',
    color: 'indigo'
  },
  {
    id: 'ACT-4',
    type: 'employee',
    text: 'Naveen Choudhury onboarded as Junior Frontend Intern',
    time: 'Yesterday',
    icon: 'UserPlus',
    color: 'blue'
  },
  {
    id: 'ACT-5',
    type: 'attendance',
    text: 'Priya Patel checked in with a 14m delay note',
    time: 'Yesterday',
    icon: 'Clock',
    color: 'amber'
  }
];
